# Generated by Django 4.0.1 on 2022-02-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colonias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='grupos_operativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='jurisdiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='origen_reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
    ]
