# Generated by Django 4.0.1 on 2022-02-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causa_accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Corporaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Daños_accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_accidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_servicio_vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_hora', models.DateField(auto_now=True)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('motivo', models.CharField(choices=[('INFRACCION', 'INFRACCION'), ('ALIMENTOS', 'ALIMENTOS'), ('CARRUSEL', 'CARRUSEL'), ('OTRO', 'OTRO')], max_length=50)),
                ('observaciones', models.TextField(max_length=200)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.grupos_operativos')),
            ],
        ),
    ]
