# Generated by Django 4.0.1 on 2022-02-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0002_causa_accidente_clasificacion_vehiculo_corporaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
