# Generated by Django 4.0.1 on 2022-02-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0005_alter_bitacora_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='fecha_hora',
            field=models.DateTimeField(null=True),
        ),
    ]
