# Generated by Django 4.0.1 on 2022-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0008_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
