# Generated by Django 4.0.1 on 2022-02-13 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0010_alter_eventos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='status',
        ),
    ]
