# Generated by Django 4.0.1 on 2022-02-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0013_rename_id_colonia_malestacionados_colonia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malestacionados',
            name='colonia',
        ),
        migrations.RemoveField(
            model_name='malestacionados',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='malestacionados',
            name='sector',
        ),
        migrations.DeleteModel(
            name='ApoyosPreventiva',
        ),
        migrations.DeleteModel(
            name='MalEstacionados',
        ),
    ]
