# Generated by Django 4.0.1 on 2022-02-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0014_remove_malestacionados_colonia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalEstacionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('elemento', models.CharField(max_length=100, null=True)),
                ('evento', models.CharField(choices=[('VEHICULO ABDANDONADO', 'VEHICULO ABDANDONADO'), ('ACTIVACION DE CODIGO ROJO', 'ACTIVACION DE CODIGO ROJO'), ('VEHICULO EXCESO DE DIMENSIONES', 'VEHICULO EXCESO DE DIMENSIONES'), ('VEHICULO DESCOMPUESTO', 'VEHICULO DESCOMPUESTO'), ('VEHICULO COCHERA', 'VEHICULO COCHERA'), ('VEHICULO EN BANQUETA', 'VEHICULO EN BANQUETA'), ('VEHICULO EN EXCLUSIVO', 'VEHICULO EN EXCLUSIVO'), ('VEHICULO EN SENTIDO CONTRARIO', 'VEHICULO EN SENTIDO CONTRARIO'), ('VEHICULO INVADE LINEA PEATONAL', 'VEHICULO INVADE LINEA PEATONAL'), ('VEHICULO EN LUGAR DISCAPACITADOS', 'VEHICULO EN LUGAR DISCAPACITADOS'), ('VEHICULO MAL ESTACIONADO', 'VEHICULO MAL ESTACIONADO'), ('VEHICULO EXCESO DE VELOCIDAD', 'VEHICULO EXCESO DE VELOCIDAD')], max_length=100)),
                ('estatus_servicio', models.CharField(max_length=50, null=True)),
                ('folio_infraccion', models.CharField(max_length=50, null=True)),
                ('numerales', models.CharField(max_length=100, null=True)),
                ('motivo_no_atencion', models.CharField(choices=[('FALSA ALARMA', 'FALSA ALARMA'), ('PUNTO ROJO', 'PUNTO ROJO'), ('FUERA DE JURISDICCION', 'FUERA DE JURISDICCION'), ('SERVICIO CANCELADO', 'SERVICIO CANCELADO'), ('NO PROPORCIONA DATOS', 'NO PROPORCIONA DATOS'), ('PERSONAL INSUFICIENTE', 'PERSONAL INSUFICIENTE')], max_length=100)),
                ('observaciones', models.TextField(max_length=200)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.colonias')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.grupos_operativos')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.origen_reporte')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='ApoyosPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('elemento', models.CharField(max_length=100, null=True)),
                ('evento', models.CharField(choices=[('INCIDENTE POR INFRACCION', 'INCIDENTE POR INFRACCION'), ('APOYO A PREVENTIVA', 'APOYO A PREVENTIVA')], max_length=100)),
                ('folio_infraccion', models.CharField(max_length=50, null=True)),
                ('unidad_preventiva', models.CharField(max_length=50, null=True)),
                ('observaciones', models.TextField(max_length=200)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('id_colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.colonias')),
                ('id_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.grupos_operativos')),
                ('id_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.sectores')),
            ],
        ),
    ]
