# Generated by Django 4.0.1 on 2022-03-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0017_alter_malestacionados_elemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoyospreventiva',
            name='elemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apoyospreventiva',
            name='folio_infraccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
