# Generated by Django 4.0.1 on 2022-04-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0018_alter_apoyospreventiva_elemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidenteVial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('folio_911', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('elemento', models.CharField(blank=True, max_length=100, null=True)),
                ('estatus_accidente', models.CharField(choices=[('ATENDIDO', 'ATENDIDO'), ('NO ATENDIDO', 'NO ATENDIDO')], max_length=50)),
                ('observaciones', models.TextField(max_length=200)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('colonia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.colonias')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.grupos_operativos')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.jurisdiccion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.origen_reporte')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='AccidenteVialNoAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_no_atencion', models.CharField(choices=[('FALSA ALARMA', 'FALSA ALARMA'), ('FUERA DE JURISDICCION', 'FUERA DE JURISDICCION'), ('INVOLUCRADOS SE RETIRARON', 'INVOLUCRADOS SE RETIRARON'), ('UNIDAD SE RETIRA DEL LUGAR', 'UNIDAD SE RETIRA DEL LUGAR'), ('NO SE PROPORCIONAN DATOS', 'NO SE PROPORCIONAN DATOS'), ('PERSONAL INSUFICIENTE', 'PERSONAL INSUFICIENTE'), ('PUNTO ROJO', 'PUNTO ROJO')], max_length=50)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.accidentevial')),
            ],
        ),
        migrations.CreateModel(
            name='AccidenteVialAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('peritos', models.CharField(blank=True, max_length=50, null=True)),
                ('policia_estatal', models.CharField(blank=True, max_length=50, null=True)),
                ('policia_federal', models.CharField(blank=True, max_length=50, null=True)),
                ('policia_preventiva', models.CharField(blank=True, max_length=50, null=True)),
                ('gurdia_nacional', models.CharField(blank=True, max_length=50, null=True)),
                ('proteccion_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('bomberos', models.CharField(blank=True, max_length=50, null=True)),
                ('grua', models.CharField(blank=True, max_length=50, null=True)),
                ('cruz_roja', models.CharField(blank=True, max_length=50, null=True)),
                ('lesionados_fem', models.IntegerField(blank=True, null=True)),
                ('lesionados_masc', models.IntegerField(blank=True, null=True)),
                ('fallecidos_fem', models.IntegerField(blank=True, null=True)),
                ('fallecidos_masc', models.IntegerField(blank=True, null=True)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('causa_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.causa_accidente')),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.accidentevial')),
                ('tipo_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.tipo_accidente')),
                ('tipo_daños', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.daños_accidente')),
            ],
        ),
        migrations.CreateModel(
            name='AccidenteConductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('nombre_conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_paterno_conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno_conductor', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio_conductor', models.CharField(blank=True, max_length=200, null=True)),
                ('sexo_conductor', models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=200, null=True)),
                ('edad_conductor', models.IntegerField(blank=True, null=True)),
                ('licencia_conductor', models.CharField(blank=True, choices=[('VIGENTE', 'VIGENTE'), ('VENCIDA', 'VENCIDA'), ('SIN LICENCIA', 'SIN LICENCIA')], max_length=50, null=True)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_vehiculo', models.IntegerField(blank=True, null=True)),
                ('placas_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('clasificacion_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.clasificacion_vehiculo')),
                ('id_accidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Omega.accidentevial')),
                ('marca_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.marca_vehiculo')),
                ('servicio_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.servicio_vehiculo')),
                ('tipo_servicio_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.tipo_servicio_vehiculo')),
            ],
        ),
    ]
