# Generated by Django 4.0.1 on 2022-04-11 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0020_alter_accidentevialatendido_id_accidente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenteconductores',
            name='id_accidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.accidentevial'),
        ),
        migrations.AlterField(
            model_name='accidentevialnoatendido',
            name='id_accidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.accidentevial'),
        ),
    ]
