# Generated by Django 4.0.1 on 2022-04-29 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0021_alter_accidenteconductores_id_accidente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculosCorralon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('ubicacion_vehiculo', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo_vehiculo', models.IntegerField(blank=True, null=True)),
                ('placas_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('color_vehiculo', models.CharField(max_length=50, null=True)),
                ('serie_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_infraccion', models.CharField(max_length=50, null=True)),
                ('numerales', models.CharField(max_length=100, null=True)),
                ('inventario', models.CharField(max_length=100, null=True)),
                ('grua', models.CharField(max_length=100, null=True)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('elemento', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(max_length=200)),
                ('estatus', models.CharField(default='ACTIVO', max_length=50)),
                ('marca_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.marca_vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Detenidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('nombre_detenido', models.CharField(max_length=50, null=True)),
                ('domicilio_detenido', models.CharField(blank=True, max_length=200, null=True)),
                ('edad_detenido', models.IntegerField(null=True)),
                ('folio_911', models.IntegerField(null=True)),
                ('folio_remision', models.IntegerField(blank=True, null=True)),
                ('ubicacion_vehiculo', models.CharField(max_length=100)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('placas_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('color_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('serie_vehiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_infraccion', models.CharField(blank=True, max_length=50, null=True)),
                ('numerales', models.CharField(blank=True, max_length=100, null=True)),
                ('inventario', models.CharField(blank=True, max_length=100, null=True)),
                ('grua', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(max_length=50, null=True)),
                ('elemento', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(max_length=200)),
                ('marca_vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Omega.marca_vehiculo')),
            ],
        ),
    ]
