# Generated by Django 4.0.1 on 2022-05-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0023_vehiculoscorralon_folio_911'),
    ]

    operations = [
        migrations.AddField(
            model_name='detenidos',
            name='estatus',
            field=models.CharField(default='ACTIVO', max_length=50),
        ),
    ]
